config/routes.rb
Rails.application.routes.draw do
  root 'accounts#index'

  devise_for :users

  resources :accounts 
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  validates :balance, numericality: { 
    greater_than_or_equal_to: 10000, 
    message: "Must have at least $10,000"
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :accounts, dependent: :destroy
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = current_user.accounts 
  end

  def show
  end

  def new
    @account = current_user.accounts.new
  end

  def create
    @account = current_user.accounts.new(account_params)
    if @account.save
      flash[:success] = "Account Created"
      redirect_to root_path
    else
      flash[:error] = "Error #{@account.errors.full_messages.first}"
      render :new
    end
  end

  def edit
  end

  def update
    if @account.update(account_params)
      redirect_to accounts_path
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
    redirect_to root_path
  end

  private
    def account_params
      params.require(:account).permit(:name, :balance)
    end

    def set_account
      @account = current_user.accounts.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    # def user_params
    #   params.require(:user)(:sign_up).permit(:email, :password, :first_name, :last_name)
    # end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/edit.html.erb
<h1>Accounts#edit</h1>
<p>Find me in app/views/accounts/edit.html.erb</p>

app/views/accounts/index.html.erb
<%= button_to 'Log out', destroy_user_session_path, method: :delete %>

<h2>Welcome <%= current_user.first_name %></h2>
<%= link_to 'Add Account', new_account_path %>

<h3>Your Accounts</h3>
<ul>
  <% @accounts.each do |account| %>
    <li>
      <%= account.name %> -$<%= account.balance %>
    </li>
  <% end %>
</ul>

app/views/accounts/new.html.erb
<h1>Add Account</h1>

<%= form_with(model: @account, local: true) do |f| %>
  <div class="input-field"> 
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>

  <%= f.label :balance %>
  <div class="input-field"> 
    <%= f.number_field :balance, min: 0, step: 0.01 %>
  </div>

  <%= f.submit nil, class: 'waves-effect waves-light btn' %>
<% end %>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBankwinter19</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class='container'>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>